### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by DevTechProfile** [michel-pi/GameOverlay.Net#36]
Hi, is it possible to support Vulkan? Would it be entirely feasible? I hope so... Mabye I can help you anyway.

**Comment by michel-pi** [comment]
Hey,
i can not work on adding other rendering backends because i have limited time, resources and knowledge.

You may want to write your own renderer which can be used with a `hwnd` render target.
You could also create a fork without the directx dependencies.

And keep in mind that this project depends highly on Microsoft products like Windows for the overlay and DirectX for the drawing.

I am also looking forward to multi-platform .Net Core implementations of WPF in the future which will enable the same functionality just using WPF as a dependency.

**Comment by DevTechProfile** [comment]
Hi, thanks for your answer. I'm time, resources and knowledge limited as well. ^^ We will see...
