### ISSUE TITLE
MultiThread Rendring so flashy

### ISSUE THREAD

**Issue by CorrM** [michel-pi/GameOverlay.Net#49]
MultiThread Rendring so flashy.
i used same as here [ #48  ]
when i use normal way, no flashy and work good !! 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5868825/75085867-3db3a600-5536-11ea-92dc-5cd72a8af1db.gif)

**Comment by michel-pi** [comment]
You need to take care of the order in which you draw stuff.
Also make sure you did everything you have done before the same way.

Multi-Threaded rendering definitely works fine.

**Comment by Azahet** [comment]
Try to lock your graphic object.
https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/lock-statement

**Comment by michel-pi** [comment]
No. There is no lock needed. Just make sure to render your objects in the correct order.

**Comment by QuiNz0r** [comment]
Did you come up with a solution? I have the same issue and I don't think it's the drawing order (you can see on the top left it'S flashing even though nothing else is rendering before or behind the yellow lines) 

locking didn't make a difference for me.

thanks again, I just donated to your btc

**Comment by michel-pi** [comment]
You can share some code or screenshots in a new issue if you want.

personally, i never had any issues but you can prove me wrong of course.

maybe i need to implement a backbuffer utility for this but let us analyse the problem in another issue.

**Comment by QuiNz0r** [comment]
I just managed to fix it it's super stable now!

instead of doing (pseudo)




```
ClearScene()
DrawScene()

lock(gfx)
{
   Paralell.Foreach 
   {
      draw stuff
   }
}

EndScene()
```

Solution:



```
ClearScene()
DrawScene()

Paralell.Foreach 
{
   lock(gfx)
   {
      draw stuff
   }
}

EndScene()
```

**Comment by michel-pi** [comment]
The code above will render anything sync rather than async due to the lock inside the loop.

you want to group your drawings and render them in the same order every frame. that's why it looks flashy.

Is async rendering really need if you say it works fine when you use lock? You could simply do a normal render loop.

**Comment by QuiNz0r** [comment]
I see, ur absolutely right it's actually sync this way...

what do you mean by group and order? I do very basic drawing like

Lines()
gfx.drawlines()

string
gfx.drawstring()
gfx.drawstring()
gfx.drawstring()

loop end

endscene()

**Comment by michel-pi** [comment]
all `draw` calls are still sync. so you can basically render each component (which may be constructed from different `draw` calls and geometry) on a different task and wait for each.

Flickering is caused by overlapping things which don't draw in the same order each frame

**Comment by QuiNz0r** [comment]
do you have simple example by any chance? I would really like to make it work

**Comment by michel-pi** [comment]
I strongly recommend to not use a multi threaded renderer because it is not needed in most cases, doesn't have too much benefits and is more complicated.

In case you are using this for a Game, you may use `Task.Run` to get all the data in an async way and wait for it with the `Task.GetAwaiter().GetResult()` method.

A simple approach to render objects in an ordered way is to organize them into simple steps of the rendering process.

You may want to render all background objects first then normal objects and then foreground objects (like ui).

Your loop must run in a deterministic way to keep the order of those objects since there is no z buffer (i believe) in d2d.

Note:
```
Most of the time it's not worth the effort. FPS and speed of execution can be optimized in better ways.

I think we should inspect your problem in another issue and find a better way to optimize your loop.
```

**Comment by QuiNz0r** [comment]
thanks for your detailed answer. I came to the same conclusion I optimized my loop and it runs really well now in a sync way, I underestimated the performance impact of some methods I called within the renderloop. Thanks again and stay healthy.
