### ISSUE TITLE
Overlay dont work with Game Stronghold Crusader

### ISSUE THREAD

**Issue by PodeCaradox** [michel-pi/GameOverlay.Net#57]
Hello,
i just wanted to use your library but i have the problem that the overlay will never be drawn above the Stronghold Crusader HD Game from firefly. Its a old Game maybe that's why. 
Here my Setup, copied the example Code, for Notepad it works:
```
 private void CreateWindow()
        {
            var gfx = new Graphics()
            {
                MeasureFPS = true,
                PerPrimitiveAntiAliasing = true,
                TextAntiAliasing = true,
                WindowHandle = ParentWindow,
                VSync = true,
            };

            _window = new GraphicsWindow(0, 0, 800, 600, gfx)
            {
                FPS = 60,
                IsTopmost = true,
                IsVisible = false
            };
            _window.SetupGraphics += _window_SetupGraphics;
            _window.DestroyGraphics += _window_DestroyGraphics;
            _window.DrawGraphics += _window_DrawGraphics;
            _window.VisibilityChanged += Test;
            _window.Create();
        }
```
I used  the WindowHandle i get from:
 
 [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr FindWindow(string lpClassName, string lpWindowName);

public void Dummy(){
_overlay.ParentWindow = FindWindow(null, "Crusader");
}

Also i don't know how to get the Class Name for the Window initialization.

Picture not ingame:
![image](https://user-images.githubusercontent.com/5760157/78700005-1443b380-7905-11ea-8f4b-1240689bcafb.png)

Ingame:
![image](https://user-images.githubusercontent.com/5760157/78700067-29b8dd80-7905-11ea-9ddf-6c840b82d74d.png)

**Comment by michel-pi** [comment]
You can use
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?view=netframework-4.8
or
https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Windows.WindowHelper.html#GameOverlay_Windows_WindowHelper_FindWindow_System_String_System_String_
to find your window instead of doing the `PInvoke` yourself.

You do not need to specify a class name for `FindWindow`. You also do not need one for the overlay because it will try to register a random one by itself.

You do not need to specify a render target (window handle) when using the `Graphics` object with the `GraphicsWindow`

Using `VSync` with a `GraphicsWindow` is also not needed since you can specify the FPS yourself.

Also, setting `IsTopmost` to true and `IsVisible` to false seems to be a bit of a conflict right?

```
var gfx = new Graphics()
{
    MeasureFPS = true,
    PerPrimitiveAntiAliasing = true,
    TextAntiAliasing = true,
};

_window = new GraphicsWindow(0, 0, 800, 600, gfx)
{
    FPS = 60,
    IsTopmost = true,
    IsVisible = true
};
```

Can you tell me the Video/Graphic settings of the game? You would either use Windowed Mode or Bypass the fullscreen mode for the overlay to be visible.

**Comment by PodeCaradox** [comment]
The Game has only Fullscreen Mode, only with the Program DxWnd i can force it to Window Mode.
Ingame it only runs with 30-60 fps.

The IsVisible was false because i only set it if the process is running and deactivate it after it closed
i also tested it with true at the start.

Wired is if i use the Program DxWnd and drag and drop the Window than it work correctly, so after the Window Moved.
![grafik](https://user-images.githubusercontent.com/5760157/78762477-303a6a00-7984-11ea-989b-61ecf0da7164.png)

I think the Stronghold Program set itself on topmost if i click in it.
(I click outside of the "Crusader "Window and after i click inside of it again it will not show the overlay)
Do you have a idea what i can do about this behavior?

**Comment by michel-pi** [comment]
it's because the game will always force itself to top again. nothing you can do there. the game is just to old

**Comment by PodeCaradox** [comment]
@michel-pi 
ok i got it to work, i just wrapped the old ddraw.dll from Stronghold with the one from here: https://github.com/elishacloud/dxwrapper
With the file it upgrade to directX 9 and in the config i added Borderless Window Mode. After this it just worked great :)
![grafik](https://user-images.githubusercontent.com/5760157/78835460-7fb67f80-79f0-11ea-8e2b-cbb32a2ad266.png)
Thanks for the library.
